In [5]:
import matplotlib.pyplot as plt
import numpy as np
from scipy import stats
import pandas as pd
import env



In [ ]:
#1 A bank found that the average number of cars waiting during the noon hour at 
# a drive-up window follows a Poisson distribution with a mean of 2 cars. 
# Make a chart of this distribution and 
# answer these questions concerning the probability of cars waiting at the drive-up window.

In [ ]:
# What is the probability that no cars drive up in the noon hour?

In [3]:
λ = 2

stats.poisson(2).pmf(0)

0.1353352832366127

In [ ]:
# What is the probability that 3 or more cars come through the drive through?

In [15]:
stats.poisson(2).sf(2)

0.32332358381693654

In [ ]:
# How likely is it that the drive through gets at least 1 car?

In [16]:
stats.poisson(2).sf(0)

0.8646647167633873

In [ ]:
#2 Grades of State University graduates are normally distributed with a mean of 3.0 
# and a standard deviation of .3. Calculate the following:
# What grade point average is required to be in the top 5% of the graduating class?

In [17]:
μ = 3.0
σ = 0.3
p = 0.05

stats.norm(3,.3).isf(.05)

3.4934560880854417

In [ ]:
# What GPA constitutes the bottom 15% of the class?

In [18]:
p = .15

stats.norm(3, .3).ppf(.15)

2.689069983151863

In [ ]:
# An eccentric alumnus left scholarship money for students in the third decile from the bottom of their class. 
# Determine the range of the third decile. 
# Would a student with a 2.8 grade point average qualify for this scholarship?

In [19]:
stats.norm(3, .3).ppf([.2, .3])

array([2.74751363, 2.84267985])

In [ ]:
# If I have a GPA of 3.5, what percentile am I in?

In [20]:
stats.norm(3, .3).cdf(3.5)

0.9522096477271853

In [ ]:
#3 A marketing website has an average click-through rate of 2%. 
# One day they observe 4326 visitors and 97 click-throughs. 
# How likely is it that this many people or more click through?

In [21]:
n = 4326
p = .02

stats.binom(4326, 0.02).sf(96)


0.13975823631416445

In [ ]:
# 4 You are working on some statistics homework consisting of 100 questions 
# where all of the answers are a probability rounded to the hundreths place. 
# Looking to save time, you put down random probabilities as the answer to each question.

# What is the probability that at least one of your first 60 answers is correct?


In [23]:
n = 60
p = 0.01

stats.binom(n,p).sf(0)

0.45284335760923855

In [ ]:
#5 The codeup staff tends to get upset when the student break area is not cleaned up. 
# Suppose that there's a 3% chance that any one student cleans the break area when they visit it, 
# and, on any given day, about 90% of the 3 active cohorts of 22 students visit the break area. 
# How likely is it that the break area gets cleaned up each day?

In [24]:
n = round(.9*3*22)
p = 0.03

stats.binom(n, p).sf(0)

0.8342199288437352

In [ ]:
# How likely is it that it goes two days without getting cleaned up?

In [25]:
stats.binom(n*2, p).pmf(0)

0.027483031992576134

In [ ]:
# All week?

In [26]:
stats.binom(n*5, p).pmf(0)

0.00012521651388091245

In [ ]:
#6 You want to get lunch at La Panaderia, but notice that the line is usually very long at lunchtime. 
# After several weeks of careful observation, you notice that the average number of people in line 
# when your lunch break starts is normally distributed with a mean of 15 and standard deviation of 3. 
# If it takes 2 minutes for each person to order, and 10 minutes from ordering to getting your food, 
# what is the likelihood that you have at least 15 minutes left to eat your food before 
# you have to go back to class? Assume you have one hour for lunch, 
# and ignore travel time to and from La Panaderia.

In [32]:
μ = 15 * 2 #change to minutes
σ = 3 * 2 #change to minutes

time_for_lunch = 60
time_to_get_food = 10
time_to_order = 2
time_to_eat = 15

avail_time = time_for_lunch - (time_to_order + time_to_get_food + time_to_eat)

stats.norm(μ, σ).cdf(avail_time)

0.6914624612740131

In [33]:
μ = 15 # people
σ = 3 # people

# 33 / 2 will give equivalent people

stats.norm(μ, σ).cdf(33/2)

0.6914624612740131

In [ ]:
#7 Connect to the employees database and find the average salary of current employees, 
# along with the standard deviation. For the following questions, 
# calculate the answer based on modeling the employees salaries with a normal distribution 
# defined by the calculated mean and standard deviation then compare this answer to the actual values present 
# in the salaries dataset.

In [ ]:
# What percent of employees earn less than 60,000?

In [49]:
url = f'mysql+pymysql://{env.user_name}:{env.pass_word}@{env.host}/employees'
query = '''SELECT *
FROM salaries s
WHERE s.to_date > NOW()'''
    
df = pd.read_sql(query, url)

In [50]:
df

emp_no  salary   from_date     to_date
0        10001   88958  2002-06-22  9999-01-01
1        10002   72527  2001-08-02  9999-01-01
2        10003   43311  2001-12-01  9999-01-01
3        10004   74057  2001-11-27  9999-01-01
4        10005   94692  2001-09-09  9999-01-01
...        ...     ...         ...         ...
240119  499995   52868  2002-06-01  9999-01-01
240120  499996   69501  2002-05-12  9999-01-01
240121  499997   83441  2001-08-26  9999-01-01
240122  499998   55003  2001-12-25  9999-01-01
240123  499999   77303  2001-11-29  9999-01-01

[240124 rows x 4 columns]

In [40]:
μ = df.salary.mean()
σ = df.salary.std()

μ, σ

(72012.23585730705, 17309.99538025198)

In [51]:
stats.norm(μ, σ).cdf(60000)

0.24385742480214423

In [ ]:
# What percent of employees earn more than 95,000?

In [41]:
stats.norm(μ, σ).sf(95000)

0.09208819199804053

In [ ]:
# What percent of employees earn between 65,000 and 80,000?

In [44]:
stats.norm(μ, σ).cdf([65000, 80000])

array([0.34270292, 0.67776349])

In [43]:
np.diff(stats.norm(μ, σ).cdf([65000, 80000]))

array([0.33506057])

In [ ]:
# What do the top 5% of employees make?

In [45]:
stats.norm(μ, σ).isf(.05)

100484.64454102777

In [46]:
df.salary.quantile(.95) #data is slighttly skewed

104225.84999999998